---
name: Backend Lint and Tests
on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request_target:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number
    || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop .#cicdBackend --command bash {0}
        working-directory: backend
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Formatting Zig
        run: zig fmt --check .
      - name: Installing JS dependencies
        run: pnpm install
      - name: Formatting JS
        run: pnpm run format:check
      - name: Linting JS
        run: pnpm run lint
      - name: Testing
        run: cd .. && nix run .#integrationTests
