---
name: DB Linting
on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
    paths:
      - "database/**"
      - ".github/workflows/db.yml"
  pull_request_target:
    paths:
      - "database/**"
      - ".github/workflows/db.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number
    || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: DB Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop .#cicdDB --command bash {0}
        working-directory: database
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Linting DB
        run: sqlfluff lint --dialect postgres .
